language:
- node_js
node_js:
- 6.2.2
script:
- npm run build-prefix
- npm run cname
deploy:
  provider: script
  script: npm run push-travis
  skip_cleanup: true
  on:
    branch:
    - master
env:
  global:
  - secure:  VyiOrYen4qOPqz8iUhbtKGHJViiqWLRuW5nk/d9unjVBgiUdsgBFH/8yP9kLV7ZRweTaS4NSdJxW/8Oitf0LYykU6WyZJhF/cvvb8gnbTOuQKGBDfiz51p84cE5xRt31ip32y6hzrOMbBGqu65ayWtFBmoWn5M9B6rbS41pCiygpL4m0J8ioPpR+GSvA6g+En6m1+ew6/P1zxMHbP22Qnm5a88BwCG4o49OxIu6ptsiG/ZYAP+XLYYj1Pzt1QXoPnejVUvQd122Y6yfJfDCj7NtAcCtlgkGheOXL3LJm71wf7ZhjSi8FOPoIjBr35yU6bMWzvJzPmYasYeROty77eRgEDcHM6Tk3RjVxHW0VAv80tiRbJ3H32SHI9MAS9LDgMofeIO5hbhYitWmFPTaeTiGaZvILaczuqye77yLXVowdZ0aZIQjuOtOfJ1o4GtqfMPaGWx4V+nuu6anER0zdQDk/FFQ73u0ElWhupMHhYy+1SwRIm+mkWOf69IllTzVgT+xRFMCcHDiC07IO8Wyg1KQGAiNdPQderNJ45WqxT8yS/7+TklIxwYI409O/7D604OpOAT/lFWYdxgE3K7KUUxnkMQJzI6gDZa0K6J0emwKW1svDitHhXXMdDE6Aw/QXcu/gf9MbpMt2/HkPt5VStYUdd11T4gJGI9OG5Mj1Ekw=
cache:
  directories:
  - node_modules
