language:
  - node_js
node_js:
  - "6.2.2"
script:
  - npm install
  - npm run build-prefix
  - npm run cname
deploy:
  provider: script
  script: npm run push-travis
  skip_cleanup: true
  on:
    branch:
    - master
env:
  global:
  - secure: "Bl5r0reWqsULfqDi+5o3BjdEjVz/dnFKc9JY8LnpViJpy7JVE99MFe/32hwXNXmrjozJnZG8d57BaZare91X4Xr0mIOMFJVUM2S1FXCYFiErZG8zY5XOD0liDGr9wu3L8J1UYHB8vZNH2xiirwekn6Bkk3tBrtR7LCvFeu5z9i1jBqP80CLYWPzZuZ/ttuk60tAzCGgmxplHeAyDTmk5+PFKuXM0YvPA6pB9/Bh5Vo2bxD6w8DFUMTy38ogxTTGJCOcpXu3ozLKe4tUMkLilNT9AIjUiOJpFAYCYTiICEJYBuo9+SsOUVm7ZOEXdZN6JJGMZAGXr+TEkLh8WSayVx5CdtUu5YuDUvBKn8ao4RuhT5IoOGI9+bPc7YnLyo9h9KChXoLumWUXm1IVPistPmkLJM+6Af1Ovh/4EpVlK7z/3Wi+6ViULmeecBGfBgYmDyC9MZr8/Y7qZn/7MXc3vba7W2Y75sTv0+hGDCbP8ISGjImGbPUkotDweiztUU5eWOmG9Ufv5U0eTdSWp+sDBr431rbdwCy82ZSaF/EmA7SBmOQ0WtBwEymxOM59g0fAeYdAs2jNU97cKO+8w0I56zW8Z4M4+YgAgdKKFroG2XK/lZmutzv/DuP+SAyldCn6ZqIZV/AhO6rvtr9V32l5wWbLyi/tkMdPuAeuwD6yaJBM="
cache:
  directories:
    - node_modules
