backend:
  name: git-gateway
  branch: next

media_folder: static/img
public_folder: /img

collections:
  - name: "site"
    label: "Site"
    files:
      - name: "site"
        label: "Algemeen"
        file: "src/pages/frontpage/site/algemeen.md"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "subTitle", name: "subTitle", widget: "string"}
          - {label: "authorPrefix", name: "authorPrefix", widget: "string"}
          - {label: "author", name: "author", widget: "string"}
          - {label: "authorLink", name: "authorLink", widget: "string"}
          - {label: "nav", name: "nav", widget: "list"}
          - {label: "tabsHeader", name: "tabsHeader", widget: "string"}
          - {label: "hashtagLink", name: "hashtagLink", widget: "string"}
          - {label: "socialText", name: "socialText", widget: "list"}
          - {label: "socialbtn", name: "socialbtn", widget: "list"}
          - {label: "description", name: "description", widget: "text"}
          - {label: "creditsTitle", name: "creditsTitle", widget: "string"}
          - {label: "Credits", name: "body", widget: "markdown"}
      - name: "form"
        label: "Formuliergegevens"
        file: "src/pages/default/form.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "fields", name: "string", widget: "list"}
          - {label: "ccField", name: "ccField", widget: "text"}
          - {label: "Submit", name: "submit", widget: "string"}
          - {label: "submitResponse", name: "submitResponse", widget: "string"}
          - {label: "submitExpandedResponse", name: "submitExpandedResponse", widget: "string"}
          - {label: "mailTo", name: "mailTo", widget: "string"}
  - name: "products"
    label: "Producten"
    folder: "src/pages/frontpage/products"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
