backend:
  name: git-gateway
  branch: next

media_folder: static/img
public_folder: /img

collections:
  - name: "general"
    label: "General"
    delete: false
    create: false
    editor:
      preview: false
    files:
      - name: "head"
        label: "Head Settings"
        file: "content/general/head.md"
        fields:
          - { label: "Head Title", name: "title", widget: "string" }
          - label: "SEO Tags"
            name: "tags"
            widget: "list"
            fields:
              - { label: "Tag", name: "tagName", widget: "string" }
          - { label: "description", name: "description", widget: "text" }
          - {
              label: "Open Graph Image",
              name: "openGraphImage",
              widget: image,
              media_folder: "../../static/img/",
            }

      - name: "header"
        label: "Header Block"
        file: "content/general/header.md"
        fields:
          - { label: "Header Title", name: "title", widget: "text" }
          - { label: "Sub Title", name: "subTitle", widget: "text" }
          - { label: "Sub Title Small", name: "subTitleSmall", widget: "text" }
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
              - { label: "prefix", name: "prefix", widget: "string" }
              - { label: "name", name: "name", widget: "string" }
              - { label: "link", name: "link", widget: "string" }
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
          - label: "Accent Color"
            name: "accentColor"
            widget: "select"
            options:
              - label: "Yellow"
                value: "#ffcc00"
              - label: "Pink"
                value: "#e00763"
            default: "#e00763"

      - name: "form"
        label: "Form Block"
        file: "content/general/form.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "fields"
            name: "fields"
            widget: "list"
            fields:
              - { label: "Field Text", name: "text", widget: "string" }
          - { label: "ccField", name: "ccField", widget: "text" }
          - { label: "Submit", name: "submit", widget: "string" }
          - {
              label: "Submit Button After Submit",
              name: "submitResponse",
              widget: "string",
            }
          - {
              label: "submitExpandedResponse",
              name: "submitExpandedResponse",
              widget: "string",
            }
          - { label: "mailTo", name: "mailTo", widget: "string" }

      - name: "credits"
        label: "Credits Block"
        file: "content/general/credits.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Authors text", name: "authorsText", widget: "string" }
          - label: "Authors"
            name: "authors"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
          - { label: "Partners text", name: "partnersText", widget: "string" }
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
          - label: "Accent Color"
            name: "accentColor"
            widget: "select"
            options:
              - label: "Yellow"
                value: "#ffcc00"
              - label: "Pink"
                value: "#e00763"
            default: "#e00763"

  - name: "landing-page"
    label: "Subsite / Landing Page"
    delete: false
    create: false
    editor:
      preview: false
    files:
      - name: "landing-page-settings"
        label: "Landing Page Settings"
        file: "content/subsites/landing-page/landing-page-settings.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Accent Color"
            name: "accentColor"
            widget: "select"
            options:
              - label: "Yellow"
                value: "#ffcc00"
              - label: "Pink"
                value: "#e00763"
            default: "#e00763"

      - name: "checkboxes-blcok"
        label: "Checkboxes Block"
        file: "content/subsites/landing-page/checkboxes-block.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Pointer button", name: "footer", widget: "string" }

      - name: "social-block"
        label: "Social Media Block"
        file: "content/subsites/landing-page/social-block.md"
        fields:
          - label: "Social Media Text"
            name: "text"
            widget: "list"
            fields:
              - { label: "Line", name: "line", widget: "string" }
          - label: "Hashtag Properties"
            name: "hashtag"
            widget: "object"
            fields:
              - { label: "Hovertext (Alt)", name: "alt", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - {
                  label: "Image",
                  name: "image",
                  widget: image,
                  media_folder: "../../../static/img/",
                }
          - label: "Social Media Buttons"
            name: "btn"
            create: false
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Link", name: "link", widget: string }
              - label: "Images"
                name: "images"
                widget: "object"
                fields:
                  - {
                      label: "Default",
                      name: "normal",
                      widget: image,
                      media_folder: "../../../static/img/",
                    }
                  - {
                      label: "Diapositive",
                      name: "inverse",
                      widget: image,
                      media_folder: "../../../static/img/",
                    }

  - name: "if-you-dont"
    label: "Subsite / If You Don't"
    delete: false
    create: false
    editor:
      preview: false
    files:
      - name: "about-settings"
        label: "About Settings"
        file: "content/subsites/if-you-dont/about/about-settings.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Accent Color"
            name: "accentColor"
            widget: "select"
            options:
              - label: "Yellow"
                value: "#ffcc00"
              - label: "Pink"
                value: "#e00763"
            default: "#e00763"

      - name: "about-block"
        label: "About Block"
        file: "content/subsites/if-you-dont/about/about-block.md"
        fields:
          - label: "Content"
            name: "body"
            widget: "markdown"
            default: ""

      - name: "additions-settings"
        label: "Additions Settings"
        file: "content/subsites/if-you-dont/additions/additions-settings.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Accent Color"
            name: "accentColor"
            widget: "select"
            options:
              - label: "Yellow"
                value: "#ffcc00"
              - label: "Pink"
                value: "#e00763"
            default: "#e00763"

      - name: "additions-block"
        label: "Additions Block"
        file: "content/subsites/if-you-dont/additions/additions-block.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Content"
            name: "body"
            widget: "markdown"
            default: ""

      - name: "sources-settings"
        label: "Sources Settings"
        file: "content/subsites/if-you-dont/sources/sources-settings.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Accent Color"
            name: "accentColor"
            widget: "select"
            options:
              - label: "Yellow"
                value: "#ffcc00"
              - label: "Pink"
                value: "#e00763"
            default: "#e00763"

      - name: "sources-block"
        label: "Sources Block"
        file: "content/subsites/if-you-dont/sources.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }

      - name: "social-block"
        label: "Social Media Block"
        file: "content/subsites/if-you-dont/social-block.md"
        fields:
          - label: "Social Media Text"
            name: "text"
            widget: "list"
            fields:
              - { label: "Line", name: "line", widget: "string" }
          - label: "Social Media Buttons"
            name: "btn"
            create: false
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Link", name: "link", widget: string }
              - label: "Images"
                name: "images"
                widget: "object"
                fields:
                  - {
                      label: "Default",
                      name: "normal",
                      widget: image,
                      media_folder: "../../../static/img/",
                    }
                  - {
                      label: "Diapositive",
                      name: "inverse",
                      widget: image,
                      media_folder: "../../../static/img/",
                    }

  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    editor:
      preview: false
    fields:
      - label: "id"
        name: "id"
        widget: "number"
        valueType: "int"
      - label: "Title (not shown outside CMS)"
        name: "title"
        widget: "string"
        default: ""
      - label: "timeToRead"
        name: "timeToRead"
        widget: "number"
        valueType: "int"
        default: 1,
      - label: "Images"
        name: "images"
        widget: "object"
        fields:
          - label: "Default"
            name: "default"
            widget: image
            media_folder: "../../static/img/"
            required: false
          - label: "Diapositive"
            name: "diapositive"
            widget: image
            media_folder: "../../static/img/"
            required: false
          - label: "Mobile (broad) Image"
            name: "mobile"
            widget: image
            media_folder: "../../static/img/"
            required: false
      - label: "Buttons"
        name: "buttons"
        widget: "list"
        fields:
          - label: "Text"
            name: "text"
            widget: "string"
            default: ""
          - label: "Link"
            name: "link"
            widget: "string"
            default: ""
      - label: "Checkbox"
        name: "checkbox"
        widget: "object"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            default: ""
          - label: "Text"
            name: "text"
            widget: "string"
            default: ""
          - label: "Mobile Nav Text"
            name: "smallText"
            widget: "string"
            default: ""
            required: true
          - label: "Visible?"
            name: "visible"
            widget: "number"
            valueType: "int"
            default: 0
            min: 0
            max: 3
            required: true
      - label: "layout"
        name: "layout"
        widget: "select"
        options:
          - label: "Visual left, content right"
            value: "horizontal-right"
          - label: "Visual right, content left"
            value: "horizontal-left"
          - label: "Visual top, content bottom"
            value: "vertical"
        default: "horizontal-right"
      - label: "Body Text"
        name: "body"
        widget: "markdown"
        default: ""
      - label: "Accent Color"
        name: "accentColor"
        widget: "select"
        options:
          - label: "Yellow"
            value: "#ffcc00"
          - label: "Pink"
            value: "#e00763"
        default: "#e00763"
      - label: "Font Family"
        name: "fontFamily"
        widget: "select"
        options:
          - label: "Nitti"
            value: "nittigrotesk-black"
          - label: "Roc"
            value: "roc-grotesk-compressed"
        default: "nittigrotesk-black"
