backend:
  name: git-gateway
  branch: next

media_folder: static/img
public_folder: /img

collections:
  - name: "site"
    label: "Site"
    delete: false
    editor:
      preview: false
    files:
      - name: "site"
        label: "Algemeen"
        file: "content/frontpage/site/algemeen.md"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "subTitle", name: "subTitle", widget: "string"}
          - {label: "authorPrefix", name: "authorPrefix", widget: "string"}
          - {label: "author", name: "author", widget: "string"}
          - {label: "authorLink", name: "authorLink", widget: "string"}
          - label: "Navigation"
            name: "nav"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Link", name: "link", widget: string }
          - {label: "tabsHeader", name: "tabsHeader", widget: "string"}
          - {label: "hashtagLink", name: "hashtagLink", widget: "string"}
          - {label: "socialText", name: "socialText", widget: "list"}
          - label: "socialbtn"
            name: "socialbtn"
            create: false
            widget: "list"
            fields:
              - { label: "text", name: "text", widget: "string" }
              - { label: "Link", name: "link", widget: string }
          - {label: "description", name: "description", widget: "text"}
          - {label: "creditsTitle", name: "creditsTitle", widget: "string"}
          - {label: "Credits", name: "body", widget: "markdown"}
      - name: "form"
        label: "Formuliergegevens"
        file: "content/frontpage/site/form.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "fields"
            name: "fields"
            widget: "list"
            fields:
              - {label: "Field Text", name: "text", widget: "string"}
          - {label: "ccField", name: "ccField", widget: "text"}
          - {label: "Submit", name: "submit", widget: "string"}
          - {label: "submitResponse", name: "submitResponse", widget: "string"}
          - {label: "submitExpandedResponse", name: "submitExpandedResponse", widget: "string"}
          - {label: "mailTo", name: "mailTo", widget: "string"}
  - name: "products"
    label: "Producten"
    folder: "content/frontpage/products"
    create: true
    editor:
      preview: false
    fields:
      - {label: "id", name: "id", widget: "number", valueType: "int"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subTitle", widget: "string"}
      - {label: "checkboxTitle", name: "checkboxTitle", widget: "string"}
      - {label: "checkboxText", name: "checkboxText", widget: "string"}
      - {label: "timeToRead", name: "timeToRead", widget: "number", valueType: "int"}
      - {label: "activated", name: "activated", widget: "boolean"}
      - {label: "image", name: "image", widget: custompathimage, customMediaPath: "../../../static/img/", rawMediaPath: "https://raw.githubusercontent.com/BUREAUDONALD-ORG/to-dont-list/next/static/img/"}
      - {label: "linkText", name: "linkText", widget: "string"}
      - {label: "link", name: "link", widget: "string"}
      - label: "layout"
        name: "layout"
        widget: "select"
        options:
          - label: "Content left, image right"
            value: "left"
          - label: "Content right, image left"
            value: "right"
        default: "left"
