backend:
  name: git-gateway
  branch: next

media_folder: static/img
public_folder: /img

collections:
  - name: "site"
    label: "Site"
    delete: false
    editor:
      preview: false
    files:
      - name: "head"
        label: "Head Informatie"
        file: "content/frontpage/site/head.md"
        fields:
          - {label: "Head Title", name: "title", widget: "string"}
          - label: "SEO Tags"
            name: "tags"
            widget: "list"
            fields:
              - {label: "Tag", name: "tagName", widget: "string"}
          - {label: "description", name: "description", widget: "text"}
          - {label: "Open Graph Image", name: "openGraphImage", widget: custompathimage, customMediaPath: "../../../static/img/", rawMediaPath: "https://raw.githubusercontent.com/BUREAUDONALD-ORG/to-dont-list/next/static/img/"}

      - name: "header"
        label: "Header"
        file: "content/frontpage/site/header.md"
        fields:
          - {label: "Header Title", name: "title", widget: "text"}
          - {label: "Sub Title", name: "subTitle", widget: "text"}
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
            - {label: "prefix", name: "prefix", widget: "string"}
            - {label: "name", name: "name", widget: "string"}
            - {label: "link", name: "link", widget: "string"}
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Link", name: "link", widget: "string"}

      - name: "checkboxes"
        label: "Checkboxes"
        file: "content/frontpage/site/checkboxes.md"
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Pointer button", name: "footer", widget: "string"}

      - name: "form"
        label: "Formuliergegevens"
        file: "content/frontpage/site/form.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "fields"
            name: "fields"
            widget: "list"
            fields:
              - {label: "Field Text", name: "text", widget: "string"}
          - {label: "ccField", name: "ccField", widget: "text"}
          - {label: "Submit", name: "submit", widget: "string"}
          - {label: "Submit Button After Submit", name: "submitResponse", widget: "string"}
          - {label: "submitExpandedResponse", name: "submitExpandedResponse", widget: "string"}
          - {label: "mailTo", name: "mailTo", widget: "string"}

      - name: "social"
        label: "Social Media"
        file: "content/frontpage/site/social.md"
        fields:
        - label: "fields"
          name: "fields"
          widget: "list"
          fields:
            - {label: "Line", name: "text", widget: "string"}
        - label: "Hashtag Properties"
          name: "hashtag"
          widget: "object"
          fields:
            - { label: "Hovertext (Alt)", name: "alt", widget: "string" }
            - { label: "Link", name: "link", widget: "string" }
            - { label: "Image", name: "image", widget: custompathimage, customMediaPath: "../../../static/img/", rawMediaPath: "https://raw.githubusercontent.com/BUREAUDONALD-ORG/to-dont-list/next/static/img/"}
        - label: "Social Media Buttons"
          name: "btn"
          create: false
          widget: "list"
          fields:
            - { label: "Text", name: "text", widget: "string" }
            - { label: "Link", name: "link", widget: string }
            - label: "Images"
              name: "images"
              widget: "object"
              fields:
                - {label: "Image", name: "image", widget: custompathimage, customMediaPath: "../../../static/img/", rawMediaPath: "https://raw.githubusercontent.com/BUREAUDONALD-ORG/to-dont-list/next/static/img/"}
                - {label: "Inversed Image", name: "imageInverse", widget: custompathimage, customMediaPath: "../../../static/img/", rawMediaPath: "https://raw.githubusercontent.com/BUREAUDONALD-ORG/to-dont-list/next/static/img/"}

      - name: "credits"
        label: "Credits"
        file: "content/frontpage/site/credits.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Authors text", name: "authorsText", widget: "string"}
          - label: "Authors"
            name: "authors"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
          - {label: "Partners text", name: "partnersText", widget: "string"}
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}

  - name: "products"
    label: "Product"
    folder: "content/frontpage/products"
    create: true
    editor:
      preview: false
    fields:
      - {label: "id", name: "id", widget: "number", valueType: "int"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "timeToRead", name: "timeToRead", widget: "number", valueType: "int"}
      - label: "Images"
        name: "images"
        widget: "object"
        fields:
          - {label: "Default", name: "default", widget: custompathimage, customMediaPath: "../../../static/img/", rawMediaPath: "https://raw.githubusercontent.com/BUREAUDONALD-ORG/to-dont-list/next/static/img/"}
          - {label: "Diapositive", name: "diapositive", widget: custompathimage, customMediaPath: "../../../static/img/", rawMediaPath: "https://raw.githubusercontent.com/BUREAUDONALD-ORG/to-dont-list/next/static/img/"}
      - label: "Button"
        name: "button"
        widget: "object"
        fields:
          - { label: "Text", name: "text", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
      - label: "Checkbox"
        name: "checkbox"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Text", name: "text", widget: "string" }
          - { label: "Visible?", name: "visible", widget: "boolean" }
      - label: "layout"
        name: "layout"
        widget: "select"
        options:
          - label: "Visual left, content right"
            value: "horizontal-right"
          - label: "Visual right, content left"
            value: "horizontal-left"
          - label: "Visual top, content bottem"
            value: "vertical"
        default: "horizontal-right"
      - label: "Body Text"
        name: "body"
        widget: "markdown"
